<?php
// Generated by ZF2's ./bin/classmap_generator.php
return array(
    'Tourist\Module'                        => __DIR__ . '/Module.php',
    'Tourist\Controller\TouristController' => __DIR__ . '/src/Tourist/Controller/TouristController.php',
    'TouristTest\Framework\TestCase'        => __DIR__ . '/tests/Tourist/Framework/TestCase.php',
    'TouristTest\SampleTest'                => __DIR__ . '/tests/Tourist/SampleTest.php',
);
