<?php echo $this->doctype(); ?>

<html lang="en">
    <head>
        <meta charset="utf-8">
        <?php echo $this->headTitle('TukPorto '. $this->translate(''))->setSeparator(' - ')->setAutoEscape(false) ?>

        <?php echo $this->headMeta()
            ->appendName('viewport', 'width=device-width, initial-scale=1.0')
            ->appendHttpEquiv('X-UA-Compatible', 'IE=edge')
        ?>

        <!-- Le styles -->
        <?php echo $this->headLink(array('rel' => 'shortcut icon', 'type' => 'image/vnd.microsoft.icon', 'href' => $this->basePath() . '/img/favicon.ico'))
                        ->prependStylesheet($this->basePath('css/style.css'))
                        ->prependStylesheet($this->basePath('img/flags.css'))
                        ->prependStylesheet($this->basePath('css/bootstrap-theme.min.css'))
                        ->prependStylesheet($this->basePath('css/bootstrap.min.css')) ?>

        <!-- Scripts -->
        <?php echo $this->headScript()
            ->prependFile($this->basePath('js/bootstrap.min.js'))
            ->prependFile($this->basePath('js/jquery.min.js'))
            ->prependFile($this->basePath('js/respond.min.js'), 'text/javascript', array('conditional' => 'lt IE 9',))
            ->prependFile($this->basePath('js/html5shiv.js'),   'text/javascript', array('conditional' => 'lt IE 9',))
        ; ?>

    </head>
    <body>
        <nav class="navbar navbar-inverse navbar-fixed-top" role="navigation">
            <div class="container">
                <div class="navbar-header">
                    <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                    </button>
                    <a class="navbar-brand" href="<?php echo $this->url('home') ?>"><img src="<?php echo $this->basePath('img/zf2-logo.png') ?>" alt="Zend Framework 2"/>&nbsp;<?php echo $this->translate('Define your course!') ?></a>
                </div>
                <div class="collapse navbar-collapse">
                    <ul class="nav navbar-nav">
                        <li class=""><a href="<?php echo $this->url('home') ?>"><?php echo $this->translate('Home') ?></a></li>

                        	<?php if(!$this->zfcUserIdentity()): ?>
                        		<li class="session">
                        		<a href="<?php echo $this->url('zfcuser/login') ?> " style="float: left;"><?php echo $this->translate('Login') ?></a>
                        		<a href="<?php echo $this->url('zfcuser/register') ?> " style="float: right;"><?php echo $this->translate('Register') ?></a>
                        		</li><!--/.navbar-user -->
                        	<?php else: ?>
                        		<li class=""><a href="<?php echo $this->url('course') ?>"><?php echo $this->translate('Courses') ?></a></li>
                        		<li class="session">
                        		<a href="<?php echo $this->url('zfcuser') ?>"><?php echo $this->zfcUserIdentity()->getUsername(); ?>
                        		<?php
                        		  $nationality = $this->getNationality($this->zfcUserIdentity()->getNationality());
                        		  $countryCode = strtolower($nationality->country_code);
                        		  $countryName = $nationality->country_name;
                        		  ?>
                        		<img src="<?php echo $this->basePath('img/blank.gif') ?>" class="flag flag-<?php echo $countryCode?>" alt="<?php echo $countryName?>>" />
                        		</a>
                        		</li><!--/.navbar-user -->
                        	<?php endif?>
                    	
                	</ul>
                    
                </div><!--/.nav-collapse -->

            </div>
        </nav>
        <div class="container">
            <?php echo $this->content; ?>
            <hr>
            <footer>
                <p>&copy;<?php echo date('Y') ?> by ISEP. <?php echo $this->translate('All rights reserved.') ?></p>
            </footer>
        </div> <!-- /container -->
        <?php echo $this->inlineScript() ?>
    </body>
</html>
