<strong>Module:</strong>
Course &raquo;
<strong>Controller:</strong>
Course &raquo;
<strong>Action:</strong>
index

<?php
$title = 'Travel Courses';
$this->headTitle($title);
?>
<h1><?php echo $this->escapeHtml($title); ?></h1>
<p>
	<a href="<?php echo $this->url('course', array('action'=>'add'));?>">Create
		new travel course</a>
</p>

<table class="table">
	<tr>
		<th>Description</th>
		<th>Date</th>
		<th>Creator</th>
		<th>&nbsp;</th>
	</tr>
<?php foreach ($courses as $course) : ?>
<tr>
		<td><?php echo $this->escapeHtml($course->description);?></td>
		<td><?php echo $this->escapeHtml($course->date);?></td>
		<?php $creator = $this->userNameById($course->user_id);?>
		<td><?php echo $this->escapeHtml($creator);?></td>
	</tr>
	<tr>
		<td>
			<?php
    $waypoints = $this->getCourseWayPoints($course->course_id);
    foreach ($waypoints as $waypoint) {
        echo $waypoint->name . " - ";
    }
    ?>
	</td>
	</tr>
<?php endforeach; ?>
</table>