<strong>Module:</strong>
Course &raquo;
<strong>Controller:</strong>
Course &raquo;
<strong>Action:</strong>
index

<?php
$title = 'Travel Courses';
$this->headTitle($title);
?>
<h1><?php echo $this->escapeHtml($title); ?></h1>
<p>
	<?php if($this->zfcUserIdentity()): ?>
	<a href="<?php echo $this->url('course', array('action'=>'add'));?>">Create new travel course</a>
	<?php endif?>
</p>

<table class="table">
	<tr>
		<th>Description</th>
		<th>Date</th>
		<th>Creator</th>
		<th>&nbsp;</th>
	</tr>
<?php foreach ($courses as $course) : ?>
<tr>
		<td><?php echo $this->escapeHtml($course->description);?></td>
		<td><?php echo $this->escapeHtml($course->date);?></td>
		<?php $creator = $this->userNameById($course->user_id);?>
		<td><?php echo $this->escapeHtml($creator);?></td>
		<td>
         <a href="<?php echo $this->url('course',
             array('action'=>'edit', 'id' => $course->course_id));?>">Edit</a>
         <a href="<?php echo $this->url('course',
             array('action'=>'delete', 'id' => $course->course_id));?>">Delete</a>
     	</td>
	</tr>
	<tr>
		<td>
		<div id="waypoints">
			<?php
    $waypoints = $this->getCourseWayPoints($course->course_id);
    foreach ($waypoints as $waypoint) {
        echo "<font color=\"grey\">".$waypoint->name . "<font> - ";
    }
    ?>
    </div>
	</td>
	</tr>
<?php endforeach; ?>
</table>