<?php
// Generated by ZF2's ./bin/classmap_generator.php
return array(
    'Course\Module'                        => __DIR__ . '/Module.php',
    'Course\Controller\CourseController' => __DIR__ . '/src/Course/Controller/CourseController.php',
    'CourseTest\Framework\TestCase'        => __DIR__ . '/tests/Course/Framework/TestCase.php',
    'CourseTest\SampleTest'                => __DIR__ . '/tests/Course/SampleTest.php',
);
