<strong>Module:</strong>
User &raquo;
<strong>Controller:</strong>
User &raquo;
<strong>Action:</strong>
add

<?php
$title = 'Create new User';
$this->headTitle($title);
?>
<h1><?php echo $this->escapeHtml($title); ?></h1>
<?php
$form->setAttribute('action', $this->url('user', array(
    'action' => 'add'
)));
$form->prepare();
echo $this->form()->openTag($form);
echo $this->formHidden($form->get('id'));
echo $this->formRow($form->get('name'));
echo $this->formRow($form->get('email'));
echo $this->formRow($form->get('password'));
echo $this->formRow($form->get('nacionality'));
echo $this->formSubmit($form->get('submit'));
echo $this->form()->closeTag();