<strong>Module:</strong> User &raquo;
<strong>Controller:</strong> User &raquo;
<strong>Action:</strong> index

<?php
// module/User/view/user/user/index.phtml:

$title = 'All users';
$this->headTitle($title);
?>
<h1><?php echo $this->escapeHtml($title); ?></h1>
<p>
	<a href="<?php echo $this->url('user', array('action'=>'add'));?>">Create new User
		</a>
</p>
<table class="table">
	<tr>
		<th>Name</th>
		<th>Email</th>
		<th>Nacionality</th>
		<th>&nbsp;</th>
	</tr>
<?php foreach ($users as $user) : ?>
<tr>
		<td><?php echo $this->escapeHtml($user->name);?></td>
		<td><?php echo $this->escapeHtml($user->email);?></td>
		<td><?php echo $this->escapeHtml($user->nacionality);?></td>
	</tr>
<?php endforeach; ?>
</table>
